"use client";

import React from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { topSellingProducts } from '@/lib/constants/mockData';
import {
  Bar,
  BarChart,
  CartesianGrid,
  ResponsiveContainer,
  Tooltip,
  XAxis,
  YAxis,
} from 'recharts';

export function TopSellers() {
  return (
    <Card className="border shadow-sm">
      <CardHeader className="flex flex-row items-center pb-2">
        <div className="grid gap-1">
          <CardTitle className="text-xl font-bold">Top Selling Products</CardTitle>
          <p className="text-sm text-muted-foreground">
            Revenue generated by best performers
          </p>
        </div>
      </CardHeader>
      <CardContent>
        <div className="h-[300px]">
          <ResponsiveContainer width="100%" height="100%">
            <BarChart
              data={topSellingProducts}
              layout="vertical"
              margin={{
                top: 5,
                right: 30,
                left: 20,
                bottom: 5,
              }}
            >
              <CartesianGrid strokeDasharray="3 3" horizontal={true} vertical={false} />
              <XAxis type="number" fontSize={12} tickFormatter={(value) => `$${value}`} />
              <YAxis 
                dataKey="name" 
                type="category" 
                fontSize={12} 
                width={150} 
                tickFormatter={(value) => value.length > 20 ? `${value.substring(0, 20)}...` : value} 
              />
              <Tooltip 
                cursor={{ fill: 'hsl(var(--muted)/0.3)' }}
                content={({ active, payload }) => {
                  if (active && payload && payload.length) {
                    return (
                      <div className="rounded-lg border bg-background p-2 shadow-sm">
                        <div className="grid gap-0.5">
                          <span className="font-bold text-sm">
                            {payload[0].payload.name}
                          </span>
                          <div className="grid grid-cols-2 gap-2 text-xs">
                            <div>
                              <span className="text-muted-foreground">Units sold: </span>
                              <span className="font-bold">{payload[0].payload.sales}</span>
                            </div>
                            <div>
                              <span className="text-muted-foreground">Revenue: </span>
                              <span className="font-bold">${payload[0].payload.revenue.toFixed(2)}</span>
                            </div>
                          </div>
                        </div>
                      </div>
                    );
                  }
                  return null;
                }}
              />
              <Bar 
                dataKey="revenue" 
                fill="hsl(var(--chart-2))" 
                radius={[0, 4, 4, 0]} 
                barSize={20} 
              />
            </BarChart>
          </ResponsiveContainer>
        </div>
      </CardContent>
    </Card>
  );
}